Models/Admission.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using NuGet.Protocol;

namespace NMK.Models;

public class Admission
{
    public int Id { get; set; }

    public required DateTime DateAdded { get; set; } 

    public DateTime? DateModified { get; set; } 
    [DataType(DataType.Date)]
    public required DateTime DateAdmitted { get; set; } 
    [ForeignKey("Patient")]
    public int? PatientId { get; set; }
    
    public Patient? Patient { get; set; }
    [ForeignKey("Doctor")]  
    public int? DoctorId { get; set; }
    
    public Doctor? Doctor { get; set; } 
    
    public bool Emergency { get; set; } = true;

    public DateTime ReportDate { get; set; }
    public string ReportText { get; set; } = string.Empty;

    public bool IsDeleted { get; set; } = false;
}

Controllers/AdmissionController.cs
using Microsoft.AspNetCore.Mvc;
using System.Text.Encodings.Web;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.IO;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NMK.Data;
using NMK.Models;
using DinkToPdf;
using DinkToPdf.Contracts;



namespace NMK.Controllers;

public class AdmissionController : Controller
{
    private readonly NMKDbContext _context;
    private readonly IConverter _converter;

    public AdmissionController(NMKDbContext context, IConverter converter)
    {
        _context = context;
        _converter = converter;
    }
    public async Task<IActionResult> Index()
    {   
        
        
        var admissions = await _context.Admissions
                        .Include(a => a.Patient)
                        .Include(a => a.Doctor)
                        .Where(a => !a.IsDeleted)
                        .ToListAsync();
        return View(admissions);
        

    }
    
    public async Task <IActionResult> FilterAdmissions(DateTime? DateFrom, DateTime? DateTo)
    {   
        
        var admissionsQuery = _context.Admissions
                        .Include(a => a.Patient)
                        .Include(a => a.Doctor)
                        .Where(a => !a.IsDeleted);

    if (DateFrom != null)
    {
        admissionsQuery = admissionsQuery.Where(a => a.DateAdmitted >= DateFrom);
    }

    if (DateTo != null)
    {
        admissionsQuery = admissionsQuery.Where(a => a.DateAdmitted <= DateTo);
    }

    var admissions = await admissionsQuery.ToListAsync();
    
    
    return PartialView("_AdmissionsTable", admissions);
        
    }


    public IActionResult AddAdmission()
    {
        ViewBag.Patients = _context.Patients.Where(p => !p.IsDeleted).ToList();
        ViewBag.Doctors = _context.Doctors.Where(d => !d.IsDeleted && d.Title == "Specijalista").ToList();
        return View();
    }

    [HttpPost]
    public IActionResult AddAdmission(Admission admission)
    {
        if (ModelState.IsValid)
        {
            admission.DateAdded = DateTime.Now;
            _context.Admissions.Add(admission);
            _context.SaveChanges();
            
            return RedirectToAction("Index");
        }

        ViewBag.Patients = _context.Patients.Where(p => !p.IsDeleted).ToList();
        ViewBag.Doctors = _context.Doctors.Where(d => !d.IsDeleted && d.Title == "Specijalista").ToList();
        return View("Error");
    }


    public IActionResult ViewAdmission(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }
        var admission = _context.Admissions
                                .Include(a => a.Patient)
                                .Include(a => a.Doctor)
                                .FirstOrDefault(a => a.Id == id);
        
        if (admission == null)
        {
            return NotFound(); 
        }

        return View(admission); 
    }

    public async Task<IActionResult> GeneratePDF(int? id)
    {
        var admission = await _context.Admissions
                                .Include(a => a.Patient)
                                .Include(a => a.Doctor)
                                .FirstOrDefaultAsync(a => a.Id == id);
        
        var htmlContent = $@"
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset='utf-8'>
            <title>NMK Nalaz</title>
            <style>
                body {{ font-family: Arial, sans-serif; margin: 0; padding: 0; }}
                h1 {{ color: #333; }}
                table {{ width: 100%; border-collapse: collapse; }}
                th, td {{ padding: 8px; border: 1px solid #ddd; }}
            </style>
        </head>
        <body>
            <h1>Medicinski nalaz</h1>
            <h3>Informacije o pacijentu</h3>
            <p><strong>Ime:</strong> {admission.Patient.NameAndSurname}</p>
            <p><strong>Datum rođenja:</strong> {admission.Patient.DateOfBirth:dd/MM/yyyy}</p>

            <h3>Informacije o liječniku</h3>
            <p><strong>Ime:</strong> {admission.Doctor.Name}</p>
            <p><strong>Prezime:</strong> dr {admission.Doctor.Surname}</p>
            <p><strong>Šifra:</strong> {admission.Doctor.DoctorCode}</p>

            <h3>Detalji nalaza</h3>
            <p><strong>Datum:</strong> {admission.ReportDate:dd/MM/yyyy}</p>
            
            <table>
                <thead>
                    <tr>
                        <th>Dijagnoza</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>{admission.ReportText}</td>
                    </tr>
                </tbody>
            </table>
            <h1>Naša Mala Klinika</h1>
        </body>
        </html>";

        var pdfDocument = new HtmlToPdfDocument
        {
            GlobalSettings = {
                ColorMode = ColorMode.Color,
                Orientation = Orientation.Portrait,
                PaperSize = PaperKind.A4
            },
            Objects = {
                new ObjectSettings
                {
                    HtmlContent = htmlContent,
                    WebSettings = { DefaultEncoding = "utf-8" }
                }
            }
        };

        var pdf = _converter.Convert(pdfDocument);

        return File(pdf, "application/pdf", $"NMK_NalazSpecijaliste_{admission.Patient.NameAndSurname}.pdf");
    }


    public IActionResult AddReport(int? id)
    {
       
        if (id == null)
        {
            return NotFound();
        }

        var admission =  _context.Admissions.Include(m => m.Patient).Include(m => m.Doctor).FirstOrDefault(m => m.Id == id);
        ViewBag.Patients = _context.Patients.Where(p => !p.IsDeleted).ToList();
        ViewBag.Doctors = _context.Doctors.Where(d => !d.IsDeleted && d.Title == "Specijalista").ToList();
               
        
        if (admission == null)
        {
            return NotFound();
        }
       
        return View(admission);
    }

    [HttpPost]
    public IActionResult AddReport(int? id, string ReportText)
    {
        var admission = _context.Admissions.Find(id);

        if (admission == null)
            {
                return NotFound();
            }
        admission.ReportDate = DateTime.Now;
        admission.DateModified = DateTime.Now;
        admission.ReportText = ReportText;
        _context.Admissions.Update(admission);
        _context.SaveChanges();
        return RedirectToAction("ViewAdmission", new { id });

    }
    
    public async Task<IActionResult> Edit(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var admission = await _context.Admissions.Include(m => m.Patient).Include(m => m.Doctor).FirstOrDefaultAsync(m => m.Id == id);
        ViewBag.Patients = _context.Patients.Where(p => !p.IsDeleted).ToList();
        ViewBag.Doctors = _context.Doctors.Where(d => !d.IsDeleted && d.Title == "Specijalista").ToList();
        
        
        if (admission == null)
        {
            return NotFound();
        }
       
        return View(admission);
    }

    private string ToString(string name)
    {
        throw new NotImplementedException();
    }

    [HttpPost]
    public async Task<IActionResult> Edit(int id, [Bind("Id,DateAdmitted,PatientId,Patient,DoctorId,Doctor,Emergency")] Admission admission)
    {
        if (id != admission.Id)
        {
            return NotFound();
        }

        if (ModelState.IsValid)
        {
            try
            {   
                admission.DateModified= DateTime.Now;
                _context.Update(admission);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!AdmissionExists(admission.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));
        }
        return View(admission);
    }

    



    [HttpPost]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        var admission = await _context.Admissions.FindAsync(id);
        if (admission != null)
        {   
            admission.IsDeleted = true;
            admission.DateModified= DateTime.Now;
            _context.Admissions.Update(admission);
            await _context.SaveChangesAsync();
        }

        
        return RedirectToAction(nameof(Index));
    }

    private bool AdmissionExists(int id)
    {
        return _context.Admissions.Any(e => e.Id == id);
    }

    }

Views/Admission/AddAdmission.cshtml
@model Admission

<h2 class="text-center my-4">Novi prijem pacijenta</h2>

<form asp-action="AddAdmission" method="post" class="form-horizontal">

   
   <div class="form-group row">
        <label for="DateAdmitted" class="col-sm-2 col-form-label">Datum i vrijeme prijema:</label>
        <div class="col-sm-10">
            <input type="datetime-local" class="form-control" id="DateAdmitted" name="DateAdmitted" required 
                   min="@DateTime.Now.ToString("yyyy-MM-ddTHH:mm")" /> 
        </div>
    </div>

    <div class="form-group row">
        <label for="PatientId" class="col-sm-2 col-form-label">Pacijent:</label>
        <div class="col-sm-10">
            <select class="form-control" id="PatientId" name="PatientId" required>
                <option value="">Izaberi pacijenta</option>
                @foreach (var patient in ViewBag.Patients)
                {
                    <option value="@patient.Id">@patient.NameAndSurname</option>
                }
            </select>
        </div>
    </div>

    <div class="form-group row">
        <label for="DoctorId" class="col-sm-2 col-form-label">Liječnik:</label>
        <div class="col-sm-10">
            <select class="form-control" id="DoctorId" name="DoctorId" required>
                <option value="">Izaberi liječnika</option>
                @foreach (var doctor in ViewBag.Doctors)
                {
                    <option value="@doctor.Id">@doctor.Name dr @doctor.Surname (@doctor.DoctorCode)</option>
                }
            </select>
        </div>
    </div>

    <div class="form-group row">
        <label for="Emergency" class="col-sm-2 col-form-label">Hitni prijem:</label>
        <div class="col-sm-10">
            
            <input type="checkbox" name="Emergency" value="true" /> Hitno
        </div>
    </div>
    


    <div class="form-group row">
        <div class="col-sm-10 offset-sm-2">
            <button type="submit" class="btn btn-primary">Dodaj novi prijem pacijenta</button>
        </div>
    </div>
</form>

Views/Admission/AddReport.cshtml
@model Admission

<h2 class="text-center my-4">Novi nalaz</h2>

<form asp-action="AddReport" method="post" class="form-horizontal">
    
    <div class="form-group row">
        <label for="admission.Patient.NameAndSurname" class="col-sm-2 col-form-label">Datum:</label>
        <div class="col-sm-10">
            <label for="ReportText" class="col-sm-2 col-form-label">@DateTime.Now.ToString("dd/MM/yyyy HH:mm")</label>
        </div>
    </div>

    <div class="form-group row">
        <label for="ReportText" class="col-sm-2 col-form-label">Detalji:</label>
        <div class="col-sm-10">
            <textarea class="form-control" id="ReportText" name="ReportText" rows="5" required></textarea>
        </div>
    </div>

    <div class="form-group row">
        <label for="admission.Patient.NameAndSurname" class="col-sm-2 col-form-label">Pacijent:</label>
        <div class="col-sm-10">
            <label for="ReportText" class="col-sm-2 col-form-label">@Model.Patient.NameAndSurname</label>
        </div>
    </div>


    

    <div class="form-group row">
        <div class="col-sm-10 offset-sm-2">
            <button type="submit" class="btn btn-primary">Dodaj novi nalaz</button>
        </div>
    </div>
</form>

Views/Admission/Edit.cshtml
@model NMK.Models.Admission

@{
    ViewData["Title"] = "Uredi prijem";
}

<h2 class="text-center my-4">Uredi Prijem</h2>

<form asp-action="Edit" method="post" class="form-horizontal">
    <input type="hidden" asp-for="Id" />

    <div class="form-group row">
        <label for="DateAdmitted" class="col-sm-2 col-form-label">Datum prijema:</label>
        <div class="col-sm-10">
            <input type="datetime-local" class="form-control" id="DateTimeAdmitted" name="DateTimeAdmitted" required 
                   min="@DateTime.Now.ToString("yyyy-MM-ddTHH:mm")" /> 
            <span asp-validation-for="DateAdmitted" class="text-danger"></span>
        </div>
    </div>

    

   <div class="form-group row">
        <label for="PatientId" class="col-sm-2 col-form-label">Pacijent:</label>
        <div class="col-sm-10">
            <select class="form-control" asp-for="PatientId" asp-items="@(new SelectList(ViewBag.Patients, "Id", "NameAndSurname"))">
                <option value="">Select Patient</option>
            </select>
        </div>
    </div>

    <div class="form-group row">
        <label for="DoctorId" class="col-sm-2 col-form-label">Liječnik:</label>
        <div class="col-sm-10">
            <select class="form-control" asp-for="DoctorId" asp-items="@(new SelectList(ViewBag.Doctors, "Id", "Surname"))">
                <option value="">Select Doctor</option>
            </select>
        </div>
    </div>

    <div class="form-group row">
        <label for="Emergency" class="col-sm-2 col-form-label">Hitni prijem:</label>
        <div class="col-sm-10">
            
            <input type="checkbox" name="Emergency" value="true" /> 
        </div>
    </div>


    <div class="form-group row">
        <div class="col-sm-10 offset-sm-2">
            <button type="submit" class="btn btn-primary">Save Changes</button>
            <a asp-action="Index" class="btn btn-secondary">Cancel</a>
        </div>
    </div>
</form>

Views/Admission/Index.cshtml
@model IEnumerable<Admission>

<h2>Prijemi</h2>


<form id="filterForm">
    <label for="DateFrom">Od datuma:</label>
    <input type="date" id="DateFrom" class="form-control" name="DateFrom" />
    
    <label for="DateTo">Do datuma:</label>
    <input type="date" id="DateTo" class="form-control" name="DateTo" />
    
    <button type="button" class="btn btn-secondary" id="filterButton">Filtriraj</button>
</form>

<div id="admissionsTable">
    
    
    @await Html.PartialAsync("_AdmissionsTable", Model)
</div>




<p>

    
</p>

<a href="/Admission/AddAdmission" class="btn btn-primary">Novi prijem pacijenta</a>

@section Scripts {
    <script type="text/javascript">
        function confirmDelete() {
            console.log('Confirm Delete function called'); 
            return confirm('Da li ste sigurni da želite izbrisati pregled?');
        }
    </script>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#filterButton').click(function () {
                var dateFrom = $('#DateFrom').val();
                var dateTo = $('#DateTo').val();

                $.ajax({
                    url: '@Url.Action("FilterAdmissions", "Admission")', 
                    type: 'GET',
                    data: { DateFrom: dateFrom, DateTo: dateTo },
                    success: function (result) {
                        
                        $('#admissionsTable').html(result);
                    },
                    error: function () {
                        console.log(dateFrom, dateTo)
                        alert('Error loading admissions');
                    }
                });
            });
        });
    </script>

    

}

Views/Admission/ViewAdmission.cshtml
@model NMK.Models.Admission

<h2 class="text-center my-4">Detalji Nalaza</h2>

<div class="row">
    <div class="col-md-6">
        <h4>Podaci o pacijentu</h4>
        <p><strong>Ime i prezime:</strong> @Model.Patient.NameAndSurname</p>
        <p><strong>Datum prijema:</strong> @Model.DateAdmitted.ToString("dd/MM/yyyy")</p>
    </div>
    <div class="col-md-6">
        <h4>Podaci o liječniku</h4>
        <p><strong>Ime i prezime:</strong> @Model.Doctor.Surname, @Model.Doctor.Name</p>
        <p><strong>Titula:</strong> @Model.Doctor.Title</p>
    </div>
</div>

<h4 class="my-4">Medicinski nalaz</h4>
<p><strong>Datum nalaza:</strong> @Model.ReportDate.ToString("dd/MM/yyyy")</p>
<p><strong>Tekst nalaza:</strong> @Model.ReportText</p>



<div class="mt-3">
    <a href="@Url.Action("Index")" class="btn btn-secondary">Povratak na prijeme</a>
    <a asp-action="GeneratePdf" asp-route-id="@Model.Id" class="btn btn-success">Preuzmi nalaz</a>
</div>

Views/Admission/_AdmissionsTable.cshtml
@model IEnumerable<Admission>

<table class="table table-bordered table-striped table-hover">
    <thead class="thead-dark">
        <tr>
            <th>Datum i vrijeme prijema</th>
            <th>Pacijent</th>
            <th>Nadležni liječnik</th>
            <th>Hitni prijem</th>
            <th>Akcije</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var admission in Model)
        {
            <tr>
                <td>@admission.DateAdmitted.ToString("dd/MM/yyyy HH:mm")</td> 
                <td>@admission.Patient.NameAndSurname</td> 
                <td>dr @admission.Doctor.Surname @admission.Doctor.Name (@admission.Doctor.DoctorCode)</td> 
                <td>@(admission.Emergency ? "Da" : "Ne")</td> 
                <td>
                    <a href="@(Url.Action("Edit", new { id = admission.Id }))" class="btn btn-primary">Uredi</a>
                    <form method="post" action="@(Url.Action("DeleteConfirmed", new { id = admission.Id }))" style="display:inline;" onsubmit="return confirmDelete();">
                        <input type="hidden" name="id" value="@admission.Id" />
                        <button type="submit" class="btn btn-danger">Obriši</button>
                    </form>
                    <a href="@(Url.Action("AddReport", new { id = admission.Id }))" class="btn btn-info">Dodaj nalaz</a>
                    <a href="@(Url.Action("ViewAdmission", new { id = admission.Id }))" class="btn btn-warning">Pogledaj nalaz</a></td>

            </tr>
        }
    </tbody>
</table>